actions:
  pre:
    vundle-install: test -e ~/.vim/bundle/Vundle.vim || ( mkdir -p ~/.vim/bundle; git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim)
    footlocker-install: test -e ~/.config/bin/footlocker || ( git clone https://github.com/Dauliac/footlocker.git /tmp && mv /tmp/footlocker/footlocker ~/.config/bin/ )
    oh-my-zsh_install: test -e ~/.oh-my-zsh || ( git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh )
    zsh_theme_install: ZSH_CUSTOM=$HOME/.oh-my-zsh/custom; test -e $ZSH_CUSTOM/themes/spaceship-prompt || ( git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" && ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme" )
    fzf_install: test -e ~/.fzf || ( git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install --no-bash --key-bindings --completion --no-update-rc )
  vundle: vim +VundleClean! +VundleInstall +VundleInstall! +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  default_bin:
    dst: ~/.config/bin
    src: config/bin
  default_compton:
    dst: ~/.config/compton
    link: true
    src: config/compton
  default_dunst:
    dst: ~/.config/dunst
    link: true
    src: config/dunst
  default_feh:
    dst: ~/.config/feh
    link: true
    src: config/feh
  default_gitconfig:
    dst: ~/.gitconfig
    link: true
    src: gitconfig
  default_gtkrc-2.0:
    dst: ~/.gtkrc-2.0
    link: true
    src: gtkrc-2.0
  default_i3:
    dst: ~/.config/i3
    link: true
    src: config/i3
  default_polybar:
    dst: ~/.config/polybar
    link: true
    src: config/polybar
  default_ranger:
    dst: ~/.config/ranger
    link: true
    src: config/ranger
  default_rofi:
    dst: ~/.config/rofi
    link: true
    src: config/rofi
  default_tmux.conf:
    dst: ~/.tmux.conf
    link: true
    src: tmux.conf
  default_vimrc:
    actions:
      - vundle-install
      - vundle
    dst: ~/.vimrc
    link: true
    src: vimrc
  default_xinitrc:
    dst: ~/.xinitrc
    link: true
    src: xinitrc
  default_xresources:
    dst: ~/.Xresources
    link: true
    src: Xresources
  default_yay:
    dst: ~/.config/yay
    link: true
    src: config/yay
  default_zprofile:
    dst: ~/.zprofile
    link: true
    src: zprofile
  default_zsh_aliases:
    dst: ~/.zsh_aliases
    link: true
    src: zsh_aliases
  default_zsh_functions:
    dst: ~/.zsh_functions
    link: true
    src: zsh_functions
  default_zshrc:
    actions:
      - oh-my-zsh_install
      - fzf_install
      - zsh_theme_install
    dst: ~/.zshrc
    link: true
    src: zshrc
  default_vimrc_min:
    dst: ~/.ssh/vimrc_min
    src: ssh/vimrc_min
    link: true
  default_bashrc_min:
    dst: ~/.ssh/bashrc_min
    src: ssh/bashrc_min
    link: true
  default_bashrc:
    link: true
    dst: ~/.bashrc
    src: ssh/bashrc_min
  default_ssh_config:
    dst: ~/.ssh/config
    src: ssh/config
    trans:
      - gpg
  media_wave.png:
    dst: ~/Pictures/wallpaper/wave.png
    src: Pictures/wallpaper/wave.png
    link: true

profiles:
  spectre:
    dotfiles:
    - default_vimrc
    - default_tmux.conf
    - default_zprofile
    - default_gtkrc-2.0
    - default_zsh_aliases
    - default_zsh_functions
    - default_zshrc
    - default_compton
    - default_bin
    - default_dunst
    - default_i3
    - default_feh
    - default_rofi
    - default_polybar
    - default_ranger
    - default_yay
    - default_ssh-agent.service
    - default_gitconfig
    - media_wave.png
    - default_xresources
    - default_xinitrc
    - default_bashrc_min
    - default_vimrc_min
  spectre_s:
    dotfiles:
    - default_ssh_config
  ghostbuster:
    dotfiles:
    - default_vimrc
    - default_tmux.conf
    - default_bashrc
    - default_bin
    - default_ranger
    - default_gitconfig
    - default_xresources

trans:
  gpg: gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}

