actions:
  pre:
    vundle-install: test -e ~/.vim/bundle/Vundle.vim || ( mkdir -p ~/.vim/bundle; git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim)
  vundle: vim +VundleClean! +VundleInstall +VundleInstall! +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  default_bin:
    dst: ~/.local/bin
    src: bin
  default_compton:
    dst: ~/.config/compton
    link: true
    src: config/compton
  default_dunst:
    dst: ~/.config/dunst
    link: true
    src: config/dunst
  default_feh:
    dst: ~/.config/feh
    link: true
    src: config/feh
  default_gitconfig:
    dst: ~/.gitconfig
    link: true
    src: gitconfig
  default_gtkrc-2.0:
    dst: ~/.gtkrc-2.0
    link: true
    src: gtkrc-2.0
  default_i3:
    dst: ~/.config/i3
    link: true
    src: config/i3
  default_polybar:
    dst: ~/.config/polybar
    link: true
    src: config/polybar
  default_ranger:
    dst: ~/.config/ranger
    link: true
    src: config/ranger
  default_rofi:
    dst: ~/.config/rofi
    link: true
    src: config/rofi
  default_tmux.conf:
    dst: ~/.tmux.conf
    link: true
    src: tmux.conf
  default_vimrc:
    actions:
      - vundle-install
      - vundle
    dst: ~/.vimrc
    link: true
    src: vimrc
  default_xinitrc:
    dst: ~/.xinitrc
    link: true
    src: xinitrc
  default_xresources:
    dst: ~/.Xresources
    link: true
    src: Xresources
  default_yay:
    dst: ~/.config/yay
    link: true
    src: config/yay
  default_profile:
    dst: ~/.profile
    link: true
    src: profile
  default_bash_aliases:
    dst: ~/.bash_aliases
    link: true
    src: bash_aliases
  default_bash_functions:
    dst: ~/.bash_functions
    link: true
    src: bash_functions
  default_bashrc:
    link: true
    dst: ~/.bashrc
    src: bashrc
  default_ssh_config:
    dst: ~/.ssh/config
    src: ssh/config
    trans:
      - gpg
  default_ssh-agent.service:
    dst: ~/.config/systemd/user/ssh-agent.service
    src: config/systemd/user/ssh-agent.service
  media_wave.png:
    dst: ~/Pictures/wallpaper/wave.png
    src: Pictures/wallpaper/wave.png
  default_zathura:
    link: true
    dst: ~/.config/zathura/zathurarc
    src: config/zathurarc
  default_libvirt:
    link: true
    dst: ~/.config/libvirt/libvirt.conf
    src: config/libvirt
  default_emoji:
    link: true
    dst: ~/.emoji
    src: emoji

profiles:
  spectre:
    dotfiles:
    - default_vimrc
    - default_tmux.conf
    - default_profile
    - default_gtkrc-2.0
    - default_bash_aliases
    - default_bash_functions
    - default_bashrc
    - default_compton
    - default_bin
    - default_dunst
    - default_i3
    - default_feh
    - default_rofi
    - default_polybar
    - default_ranger
    - default_yay
    - default_ssh-agent.service
    - default_gitconfig
    - media_wave.png
    - default_xresources
    - default_zathura
    - default_xinitrc
    - default_libvirt
    - default_emoji
  spectre_s:
    dotfiles:
    - default_ssh_config

trans:
  gpg: gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}

