theme = "gruvbox-dark"

icons = "awesome"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "custom"
on_click = "sshutdown"
cycle = ["echo "]

[[block]]
block = "custom"
on_click = "sreboot"
cycle = ["echo "]

[[block]]
block = "custom"
on_click = "xautolock -locknow"
cycle = ["echo "]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "enp0s31f6"
ssid = false
ip = true
speed_up = true
graph_up = true
interval = 4

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
device = "BAT0"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
